# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPl9-nYr-uzSdgwjPzakvQIcaEoO3bX5
"""

import pandas as pd
import numpy as np
import random
from pathlib import Path

from re import sub
master = pd.read_csv("/content/Master_6.csv")
master
types_to_subtypes = {
  # 'American Cuisine' : ['Burger', 'Steakhouse', 'Breakfast'],
  # 'Asian Cuisine' : ['Chinese', 'Korean', 'Japanese', 'Thai', 'Indian'],
  # 'Latin Cuisine' : ['Mexican', 'Tapas', 'Carribean'],
  # 'Drinks/Dessert' : ['Boba', 'Coffee', 'Ice Cream']    
  'Department' : ['Budget brands', 'Name brands'],
  'Thrift' : ['Boutique', 'Thrift Store Chains', 'Vintage'],
  'Shoes' : ['Running Shoes', 'Sneaker', 'Outdoors', 'Shoe Warehouse']  
  }

types_to_subtypes_list = types_to_subtypes.keys()

subtype_proportions = {
  # 'American Cuisine' : [0.75, 0.25, 0.3],
  # 'Asian Cuisine' : [0.4, 0.5, 0.8, 0.1, 0.3],
  # 'Latin Cuisine' : [0.6, 0.2, 0.4],
  # 'Drinks/Dessert' : [0.8, 0.4, 0.7]    
  'Department' : [0.7, 0.4],
  'Thrift' : [0.3, 0.8, 0.25],
  'Shoes' : [0.3, 0.7, 0.35, 0.45]  
}

subtype_dataframes = {}

for subtype in types_to_subtypes_list:
  df = master[master[subtype] == 1][['Region', subtype]]
  df = df.groupby(['Region'], as_index = False).count()
  df = df.rename({subtype: 'Count'}, axis = 1)
  subtype_dataframes[subtype] = df

# repeat for each data frame (american, asian, etc)
for types in subtype_dataframes.keys():
  df = subtype_dataframes[types]
  # for each subtype in each data frame
  for j in range(len(types_to_subtypes[types])):
    subtype = types_to_subtypes[types][j]
    temp = []
    # for each region  
    for i in range(len(subtype_dataframes[types])):
      region_count = df['Count'].values[i]
      max_prob = subtype_proportions[types][j]
      min_prob = max(subtype_proportions[types][j] - 0.5, 0)
      temp.append(np.ceil(region_count * random.uniform(min_prob, max_prob)))
    df[subtype] = temp

subtype_dataframes
for frame in subtype_dataframes.keys():
  filepath = Path('/content/{}'.format(frame)) 
  subtype_dataframes[frame].to_csv(filepath)
subtype_dataframes

# american_subset = master[master['American Cuisine'] == 1].filter(items=['Region', 'American Cuisine'])
# american_subset = american_subset.groupby(['Region'], as_index = False).count()





# filepath = Path('/content/american.csv') 
# american_subset.to_csv(filepath)

